### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by Ecehema** [fadhli-69/App-MyAudioClassification#1]
2024-11-12 17:17:11.864 15597-15597 AndroidRuntime          com.example.myaudioclassification    E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.myaudioclassification, PID: 15597
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "libmediapipe_tasks_audio_jni.so" not found
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at com.google.mediapipe.tasks.audio.core.BaseAudioTaskApi.<clinit>(BaseAudioTaskApi.java:40)
                                                                                                    	at com.example.myaudioclassification.AudioClassifierHelper.initClassifier(AudioClassifierHelper.kt:52)
                                                                                                    	at com.example.myaudioclassification.AudioClassifierHelper.<init>(AudioClassifierHelper.kt:31)
                                                                                                    	at com.example.myaudioclassification.AudioClassifierHelper.<init>(AudioClassifierHelper.kt:17)
                                                                                                    	at com.example.myaudioclassification.MainActivity.initializeAudioClassifierHelper(MainActivity.kt:80)
                                                                                                    	at com.example.myaudioclassification.MainActivity.onCreate(MainActivity.kt:24)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by fadhli-69** [comment]
Run only with real device, emulator cant catch the task audio

**Comment by fadhli-69** [comment]
Run only with real device, emulator cant catch the task audio
